# Generated by Django 5.0.7 on 2024-07-31 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_remove_access_door'),
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='access',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='access.access', verbose_name='accesses'),
            preserve_default=False,
        ),
    ]
