# Generated by Django 5.0.7 on 2024-08-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
        ('door', '0003_remove_door_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='name',
        ),
        migrations.AddField(
            model_name='door',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='DeviceId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door',
            name='port',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='door',
            name='type',
            field=models.CharField(choices=[('E', 'e'), ('S', 's'), ('E/S', 'e/s')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
