# Generated by Django 5.0.7 on 2024-08-01 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0004_remove_door_name_door_device_door_port_door_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='doorNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
