# Generated by Django 5.0.7 on 2024-08-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('door', '0005_door_doornumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='door',
            name='port',
        ),
    ]
