# Generated by Django 5.0.7 on 2024-08-01 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0012_remove_access_door_access_doors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='access.access', verbose_name='AccessId')),
            ],
        ),
    ]
