# Generated by Django 5.0.7 on 2024-08-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_rename_gamename_assignment_name_and_more'),
        ('role', '0001_initial'),
        ('timezone', '0007_remove_timezone_access_timezone_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='role',
            name='startTime',
        ),
        migrations.AddField(
            model_name='role',
            name='assignment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='AssignmentId'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='role',
            name='timezone',
            field=models.ManyToManyField(to='timezone.timezone', verbose_name='TimezoneId'),
        ),
        migrations.AddField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('E', 'e'), ('S', 's'), ('E/S', 'e/s')], default=1, max_length=5),
            preserve_default=False,
        ),
    ]
