# Generated by Django 5.0.7 on 2024-08-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_assignment_access'),
        ('role', '0002_remove_role_endtime_remove_role_starttime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assignment.assignment', verbose_name='AssignmentId'),
        ),
    ]
