# Generated by Django 5.0.7 on 2024-08-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0003_alter_role_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='assignment',
        ),
    ]
