# Generated by Django 5.0.7 on 2024-08-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_remove_access_doors_access_doors'),
        ('role', '0004_remove_role_assignment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='access',
        ),
        migrations.AddField(
            model_name='role',
            name='access',
            field=models.ManyToManyField(to='access.access', verbose_name='AccessId'),
        ),
    ]
