# Generated by Django 5.0.7 on 2024-08-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('role', '0005_remove_role_access_role_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='roleName',
        ),
    ]
