# Generated by Django 5.0.7 on 2024-08-01 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_remove_access_door_access_doors'),
        ('timezone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='access',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='access.access'),
            preserve_default=False,
        ),
    ]
