# Generated by Django 5.0.7 on 2024-08-05 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0002_timezone_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='FriTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='FriTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='FriTime3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol1Time1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol1Time2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol1Time3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol2Time1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol2Time2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol2Time3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol3Time1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol3Time2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='Hol3Time3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='MonTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='MonTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='MonTime3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='SatTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='SatTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='SatTime3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='SunTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='SunTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='SunTime3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='ThuTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='ThuTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='ThuTime3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='TueTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='TueTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='TueTime3',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='WedTime1',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='WedTime2',
        ),
        migrations.RemoveField(
            model_name='timezone',
            name='WedTime3',
        ),
        migrations.AddField(
            model_name='timezone',
            name='endtTime',
            field=models.TimeField(default=datetime.datetime(2024, 8, 5, 11, 17, 39, 809493)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timezone',
            name='startTime',
            field=models.TimeField(default=datetime.datetime(2024, 8, 5, 11, 17, 49, 544798)),
            preserve_default=False,
        ),
    ]
