# Generated by Django 5.0.7 on 2024-08-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0003_remove_timezone_fritime1_remove_timezone_fritime2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timezone',
            old_name='endtTime',
            new_name='endTime',
        ),
    ]
