# Generated by Django 5.0.7 on 2024-08-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0004_rename_endttime_timezone_endtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='endTime',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='startTime',
            field=models.DateField(),
        ),
    ]
