# Generated by Django 5.0.7 on 2024-08-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0005_alter_timezone_endtime_alter_timezone_starttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='endTime',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='timezone',
            name='startTime',
            field=models.DateTimeField(),
        ),
    ]
