# Generated by Django 5.0.7 on 2024-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0007_remove_timezone_access_timezone_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='timezone',
            name='is_sync',
            field=models.BooleanField(default=False),
        ),
    ]
