# Generated by Django 5.0.7 on 2025-02-04 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0008_timezone_is_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timezone',
            name='is_sync',
        ),
    ]
