# Generated by Django 5.0.7 on 2025-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timezone', '0009_remove_timezone_is_sync'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timezone',
            name='TimezoneId',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
