# Generated by Django 5.0.7 on 2024-08-08 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('bracelet_id', models.CharField(max_length=50)),
                ('active', models.BooleanField()),
                ('color', models.CharField(max_length=50)),
                ('add_date', models.DateTimeField(null=True)),
            ],
        ),
    ]
