# Generated by Django 5.0.7 on 2024-08-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
