# Generated by Django 5.0.7 on 2024-08-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet', '0002_alter_bracelet_add_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
