# Generated by Django 5.0.7 on 2024-08-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bracelet', '0003_alter_bracelet_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bracelet',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('black', 'Black'), ('white', 'White'), ('orange', 'Orange'), ('purple', 'Purple'), ('pink', 'Pink'), ('brown', 'Brown'), ('gray', 'Gray'), ('cyan', 'Cyan'), ('magenta', 'Magenta'), ('lime', 'Lime'), ('indigo', 'Indigo'), ('violet', 'Violet'), ('gold', 'Gold'), ('silver', 'Silver'), ('maroon', 'Maroon'), ('navy', 'Navy'), ('olive', 'Olive'), ('teal', 'Teal'), ('aqua', 'Aqua'), ('fuchsia', 'Fuchsia'), ('coral', 'Coral'), ('salmon', 'Salmon'), ('khaki', 'Khaki'), ('turquoise', 'Turquoise'), ('plum', 'Plum'), ('orchid', 'Orchid'), ('sienna', 'Sienna')], max_length=50),
        ),
    ]
