# Generated by Django 5.0.7 on 2024-07-24 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
