# Generated by Django 5.0.7 on 2024-07-24 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('superuser', 'Superuser'), ('user', 'User')], default='user', max_length=20),
        ),
    ]
