# Generated by Django 5.0.7 on 2024-07-24 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
