# Generated by Django 5.0.7 on 2024-09-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='youssefbenlallahom03@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
