# Generated by Django 5.0.7 on 2024-09-03 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_user_can_manage_access_user_can_manage_assignment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
