# Generated by Django 5.0.7 on 2024-09-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_manage_door',
            field=models.BooleanField(default=False),
        ),
    ]
