# Generated by Django 5.0.7 on 2024-07-31 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('DeviceId', models.AutoField(primary_key=True, serialize=False)),
                ('device_ip', models.GenericIPAddressField(unique=True)),
                ('device_name', models.CharField(max_length=50)),
                ('nb_port', models.IntegerField()),
            ],
        ),
    ]
