# Generated by Django 5.0.7 on 2024-08-13 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='nb_port',
            new_name='nb_doors',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='device_name',
            new_name='port',
        ),
    ]
