# Generated by Django 5.0.7 on 2025-04-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_rename_nb_port_device_nb_doors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='nb_doors',
            field=models.IntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='device',
            name='port',
            field=models.CharField(default='4370', max_length=50),
        ),
    ]
