# Generated by Django 5.0.7 on 2024-07-29 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
        ('timezone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAuth',
            fields=[
                ('client_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.client', verbose_name='user_id')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('AuthorizeDoorId', models.CharField(max_length=50)),
                ('AuthorizeTimezoneId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timezone.timezone', verbose_name='TimezoneId')),
            ],
        ),
    ]
