# Generated by Django 5.0.7 on 2024-07-29 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('clientAuth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientauth',
            name='client_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='client.client', verbose_name='client_id'),
        ),
    ]
