# Generated by Django 5.0.7 on 2024-07-31 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('num_port', models.IntegerField()),
                ('status', models.CharField(choices=[('E', 'e'), ('S', 's')], max_length=1)),
                ('AccessId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='AccessId')),
            ],
        ),
    ]
