# Generated by Django 5.0.7 on 2024-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_rename_accessid_access_device'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='num_port',
            new_name='entry_port',
        ),
        migrations.RemoveField(
            model_name='access',
            name='status',
        ),
        migrations.AddField(
            model_name='access',
            name='exit_port',
            field=models.IntegerField(null=True),
        ),
    ]
