# Generated by Django 5.0.7 on 2024-07-31 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_rename_num_port_access_entry_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='exit_port',
            field=models.IntegerField(),
        ),
    ]
