# Generated by Django 5.0.7 on 2024-07-31 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_access_exit_port'),
        ('device', '0001_initial'),
        ('door', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='entry_port',
            new_name='port',
        ),
        migrations.RemoveField(
            model_name='access',
            name='exit_port',
        ),
        migrations.RemoveField(
            model_name='access',
            name='name',
        ),
        migrations.AddField(
            model_name='access',
            name='door',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='door.door', verbose_name='accesses'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='type',
            field=models.CharField(choices=[('E', 'e'), ('S', 's')], default='null', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='device.device', verbose_name='DeviceId'),
        ),
    ]
