# Generated by Django 5.0.7 on 2024-08-01 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_access_door'),
        ('door', '0003_remove_door_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='device',
        ),
        migrations.RemoveField(
            model_name='access',
            name='door',
        ),
        migrations.RemoveField(
            model_name='access',
            name='port',
        ),
        migrations.RemoveField(
            model_name='access',
            name='type',
        ),
        migrations.AddField(
            model_name='access',
            name='access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='door.door'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
