# Generated by Django 5.0.7 on 2024-08-01 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_rename_door_access_door_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='door_list',
            new_name='door',
        ),
    ]
