# Generated by Django 5.0.7 on 2024-08-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_rename_door_list_access_door'),
        ('door', '0005_door_doornumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='door',
        ),
        migrations.AddField(
            model_name='access',
            name='doors',
            field=models.ManyToManyField(related_name='accesses', to='door.door'),
        ),
    ]
