# Generated by Django 5.0.7 on 2024-08-13 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0012_remove_access_door_access_doors'),
        ('door', '0006_remove_door_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='doors',
        ),
        migrations.AddField(
            model_name='access',
            name='doors',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='door.door'),
            preserve_default=False,
        ),
    ]
