# Generated by Django 5.0.7 on 2024-08-14 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_remove_access_doors_access_doors'),
        ('door', '0006_remove_door_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='doors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doors', to='door.door'),
        ),
    ]
