# Generated by Django 5.0.7 on 2024-08-15 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0014_alter_access_doors'),
        ('door', '0006_remove_door_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='doors',
        ),
        migrations.AddField(
            model_name='access',
            name='doors',
            field=models.ManyToManyField(related_name='accesses', to='door.door'),
        ),
    ]
