# Generated by Django 5.0.7 on 2024-08-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_remove_access_doors_access_doors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='access',
            old_name='name',
            new_name='GameName',
        ),
    ]
