# Generated by Django 5.0.7 on 2024-08-01 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braceletId', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('startTime', models.TimeField()),
                ('gameName', models.CharField(max_length=50)),
                ('gameDuration', models.IntegerField()),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='role.role', verbose_name='RoleId')),
            ],
        ),
    ]
