# Generated by Django 5.0.6 on 2025-05-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('braceletId', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('access', models.CharField(choices=[('ChillRoom', 'ChillRoom'), ('GameOn', 'GameOn'), ('Office', 'Office'), ('Escape1', 'Escape1'), ('Escape2', 'Escape2'), ('Escape3', 'Escape3'), ('AxeThrowing', 'AxeThrowing')], max_length=50)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
            ],
        ),
    ]
