# Generated by Django 5.0.6 on 2025-05-03 23:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='access',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='startTime',
        ),
        migrations.CreateModel(
            name='AccessPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('ChillRoom', 'ChillRoom'), ('GameOn', 'GameOn'), ('Office', 'Office'), ('Escape1', 'Escape1'), ('Escape2', 'Escape2'), ('Escape3', 'Escape3'), ('AxeThrowing', 'AxeThrowing')], max_length=50)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_periods', to='assignment.assignment')),
            ],
        ),
    ]
