# Generated by Django 5.0.7 on 2024-08-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0013_remove_access_doors_access_doors'),
        ('assignment', '0002_rename_gamename_assignment_name_and_more'),
        ('timezone', '0007_remove_timezone_access_timezone_access'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment_Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access_id', to='access.access')),
                ('assignment_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_id', to='assignment.assignment')),
                ('timezone_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timezone_id', to='timezone.timezone')),
            ],
        ),
    ]
