# Generated by Django 5.0.7 on 2024-08-27 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0016_rename_name_access_gamename'),
        ('assignment', '0004_assignment_role'),
        ('role', '0006_rename_name_role_rolename'),
        ('timezone', '0007_remove_timezone_access_timezone_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='access',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='access.access'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignment',
            name='timezone',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='timezone.timezone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='braceletId',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='role.role'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment_access',
            name='access_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_accesses', to='access.access'),
        ),
        migrations.AlterField(
            model_name='assignment_access',
            name='assignment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_accesses', to='assignment.assignment'),
        ),
        migrations.AlterField(
            model_name='assignment_access',
            name='timezone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_accesses', to='timezone.timezone'),
        ),
    ]
