# Generated by Django 5.0.7 on 2024-08-27 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignment_access_assignment_timezone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='access',
            new_name='access_ids',
        ),
        migrations.RenameField(
            model_name='assignment',
            old_name='timezone',
            new_name='timezone_ids',
        ),
    ]
