# Generated by Django 5.0.7 on 2024-08-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0016_rename_name_access_gamename'),
        ('assignment', '0006_rename_access_assignment_access_ids_and_more'),
        ('timezone', '0007_remove_timezone_access_timezone_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='access_ids',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='timezone_ids',
        ),
        migrations.AddField(
            model_name='assignment',
            name='access_ids',
            field=models.ManyToManyField(related_name='assignments', to='access.access'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='timezone_ids',
            field=models.ManyToManyField(related_name='assignments', to='timezone.timezone'),
        ),
    ]
