# Generated by Django 5.0.7 on 2024-08-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_remove_assignment_access_ids_and_more'),
        ('role', '0006_rename_name_role_rolename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='role',
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.ManyToManyField(related_name='role_id', to='role.role'),
        ),
    ]
