# Generated by Django 5.0.7 on 2024-08-30 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_remove_assignment_role_assignment_role'),
        ('role', '0006_rename_name_role_rolename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='role',
        ),
        migrations.AddField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='role.role'),
        ),
    ]
