# Generated by Django 5.0.7 on 2024-08-31 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0011_rename_role_ids_assignment_role'),
        ('role', '0006_rename_name_role_rolename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='role.role'),
        ),
    ]
